### ISSUE TITLE
App doesn't work on YT 12.19.56 (latest one)

### ISSUE THREAD

**Issue by DoomD95** [pylerSM/YouTubeBackgroundPlayback#321] opened 2017-05-21 08:53 UTC
App doesn't work on YT 12.19.56 (latest one). I have to use the older version to get back your app's function. Please check it out and Update! Thank you!

**Comment by DoomD95** [comment] 2017-05-21 08:55
I already install YoutubePlaybackBackground 2.0.1

**Comment by DoomD95** [comment] 2017-05-21 08:56
I already installed YoutubePlaybackBackground 2.0.1

**Comment by th3an7** [comment] 2017-05-21 12:57
Can you please check if it's fixed now? I guess I made a little mistake while updating the code :P

**Comment by Oskramos** [comment] 2017-05-21 14:50
I have the same problem

**Comment by DoomD95** [comment] 2017-05-21 15:28
Unfortunately, the problem's still there. @th3an7

**Comment by jackbleu** [comment] 2017-05-21 18:51
Yup, I was wondering if it's only me, looks like not.

**Comment by Ithilden** [comment] 2017-05-22 13:51
Yeah, I'm having the same issue still.

**Comment by Ockaie** [comment] 2017-05-25 19:18
Yeah same here, problem persists.

**Comment by Ithilden** [comment] 2017-05-25 19:34
I really hope it gets fixed relatively soon. This is by far the best modification to youtube.

**Comment by trungkienvevo** [comment] 2017-05-26 11:05
I hope you can fix it sooner.

**Comment by Radioplayer1997** [comment] 2017-05-26 19:15
Same issue on latest update.

**Comment by Rehayi** [comment] 2017-05-26 21:09
Same problem. If I had known that, I wouldn't have downloaded.

**Comment by LiorHaim** [comment] 2017-05-26 23:59
Same problem here...

**Comment by th3an7** [comment] 2017-05-27 00:08
You can temporarily use Lucky Patcher https://github.com/pylerSM/YouTubeBackgroundPlayback/issues/293#issuecomment-298825442

I've checked every single line of code and I still don't know, why is it not working...
@esgie @pylerSM... can you guys check it out?

**Comment by LiorHaim** [comment] 2017-05-27 00:09
Until the problem is solved, you can uninstall updates of the YouTube and downgrade to the previous version, where it worked:
http://www.apkmirror.com/apk/google-inc/youtube/youtube-12-17-54-release/

Just choose the right version for your phone..

**Comment by Radioplayer1997** [comment] 2017-05-27 00:11
Hope the issue gets solved quickly.

**Comment by nampud** [comment] 2017-05-27 15:48
According to logcat, the version code is different than expected:
```
05-27 17:39:06.591 I/YTBackgroundPlayback(6262): No hook details were found for the version of YouTube installed on your device. [vc:1219563300]
05-27 17:39:06.591 I/YTBackgroundPlayback(6262): Using the fall-back hook details for YouTube as a last resort.
05-27 17:39:06.596 W/YTBackgroundPlayback(6262): One of the hooks could not be applied: java.lang.ClassNotFoundException: com.google.android.libraries.youtube.player.background.BackgroundTransitioner
05-27 17:39:06.600 W/YTBackgroundPlayback(6262): One of the hooks could not be applied: java.lang.ClassNotFoundException: com.google.android.libraries.youtube.innertube.model.PlayabilityStatusModel
05-27 17:39:06.604 W/YTBackgroundPlayback(6262): One of the hooks could not be applied: java.lang.ClassNotFoundException: com.google.android.apps.youtube.app.background.BackgroundSettings
05-27 17:39:06.607 W/YTBackgroundPlayback(6262): One of the hooks could not be applied: java.lang.ClassNotFoundException: com.google.android.apps.youtube.app.background.BackgroundSettings
05-27 17:39:06.611 W/YTBackgroundPlayback(6262): One of the hooks could not be applied: java.lang.ClassNotFoundException: com.google.android.libraries.youtube.common.util.PackageUtil
05-27 17:39:06.611 I/YTBackgroundPlayback(6262): Done applying the hooks. [vc:1219563300]
```
Version multiplier is 1000, so version is 1219563300/1000=1219563, the json has 121956

**Comment by th3an7** [comment] 2017-05-27 17:35
@nampud thanks for posting that log - it REALLY helped :D

Now, can someone else check if there is the same error? Version number can
differ according to device DPI, CPU arch and/or Android version...

1219563300 is arm, nodpi, 5.0+ version...

If someone with different CPU arch (x86/arm64) could check if log displays
different numbers (ie. 3400 for arm64 and 3700 for x86 - both for nodpi
5.0+)

If yes, please say so, so we could change version numbers in .json

**Comment by sidnov** [comment] 2017-05-27 19:00
How do I get that log you talking about? I have an arm64 (Helio P10)

**Comment by th3an7** [comment] 2017-05-27 19:14
Check Xposed app (somwhere there should be log)

**Comment by AuroraWright** [comment] 2017-05-27 20:26
The xposed log doesn't report this, you need to check the logcat (I have an arm device so I can't be of help)

**Comment by th3an7** [comment] 2017-05-27 21:37
@Aurora does your phone uses YouTube app with specific DPI or nodpi version?

Everyone else who have other CPU arch. - check adb logcat as @Aurora
suggested for getting logs.

**Comment by MichelTenVoorde** [comment] 2017-05-27 22:31
My logcat says:

`No hook details were found for the version of YouTube installed on your device. [vc: 1219563330]`

**Comment by th3an7** [comment] 2017-05-27 23:24
As I thought - @MichelTenVoorde and @nampud logs proves that version is changing depending on device CPU arch/OS version/DPI...

Now, is there anyone who knows how to add some kind of wildcard for version naming in .json (ie. latest update would look like "121956****")

**Comment by Ithilden** [comment] 2017-05-28 00:50
The issue still seems to persist for me, and I can't seem to locate the log, but will be willing to post it if told where to find it.

**Comment by th3an7** [comment] 2017-05-28 01:39
@Ithilden use adb logcat to get the log - you need a PC to do this :)

**Comment by trungkienvevo** [comment] 2017-05-28 02:58
How can i fix the error?

**Comment by AuroraWright** [comment] 2017-05-28 02:59
05-28 04:51:39.822 11580 11580 I YTBackgroundPlayback: No hook details were found for the version of YouTube installed on your device. [vc:1219563340]
05-28 04:51:39.822 11580 11580 I YTBackgroundPlayback: Using the fall-back hook details for YouTube as a last resort.
05-28 04:51:39.825 11580 11580 W YTBackgroundPlayback: One of the hooks could not be applied: java.lang.ClassNotFoundException: com.google.android.libraries.youtube.player.background.BackgroundTransitioner
05-28 04:51:39.828 11580 11580 W YTBackgroundPlayback: One of the hooks could not be applied: java.lang.ClassNotFoundException: com.google.android.libraries.youtube.innertube.model.PlayabilityStatusModel
05-28 04:51:39.831 11580 11580 W YTBackgroundPlayback: One of the hooks could not be applied: java.lang.ClassNotFoundException: com.google.android.apps.youtube.app.background.BackgroundSettings
05-28 04:51:39.834 11580 11580 W YTBackgroundPlayback: One of the hooks could not be applied: java.lang.ClassNotFoundException: com.google.android.apps.youtube.app.background.BackgroundSettings
05-28 04:51:39.837 11580 11580 W YTBackgroundPlayback: One of the hooks could not be applied: java.lang.ClassNotFoundException: com.google.android.libraries.youtube.common.util.PackageUtil
05-28 04:51:39.837 11580 11580 I YTBackgroundPlayback: Done applying the hooks. [vc:1219563340]

**Comment by lobezno223** [comment] 2017-05-28 03:15
Hi, same problem here. 
Since upgrading YT to 12.19.56 the background playing doesn't autostart. 
My device specs are: Android KitKat 4.4.2 - 320dpi - ARMv7 Processor rev 3 (v7|)

**Comment by AuroraWright** [comment] 2017-05-28 03:16
So I'm not a Java coder but the issue is quite simple it seems. Basically the version codes, up until the previous YT version, were made of 9 digits. Now they're made of 10 digits. The division by 1000 was sufficient until the previous 1000 to filter out the differences in architectures/DPI sizes; but now a division by 10000 is needed. So you'd need to drop support for all the previous versions (since 10000 causes trouble/some old versions would have the same result when divided by 10000), and change the version id to 121956

**Comment by bishoppp** [comment] 2017-05-28 07:12
i updated youtube 2 days ago and this module is not working... hope ull fix it :)

**Comment by th3an7** [comment] 2017-05-28 08:49
@AuroraWright I've seen your solution but I don't think @pylerSM would like to drop those all those previous version, at least not right now...

What about this: https://github.com/th3an7/YouTubeBackgroundPlayback/commit/540a7967c21effb180c1cd2f12fcd093a4a3ed7f
Would that work?

If not, I could build new module .apk with newly created json file for further updates

**Comment by MichelTenVoorde** [comment] 2017-05-28 08:52
@th3an7, it still doesn't work. In my case, hooks-1.json should have 1219563 instead of 1219560 as the version string to match. May I suggest just looking at the leftmost 6 digits of the version number? Should work as far as I can tell. If version number scheming changes in the future, oh well, that'd be something to worry about later.

**Comment by MichelTenVoorde** [comment] 2017-05-28 08:56
Being desperate for background playback 🌝, fixed it locally for now by changing line 70 of YouTubeBackgroundPlayback.java to:

`JSONArray hooks = hooksFile.optJSONArray("1219560");`

**Comment by th3an7** [comment] 2017-05-28 09:03
That is one solution :)

I will probably build new apk - please check Xposed repo for updates... it should be available in max. 30 min

**Comment by nampud** [comment] 2017-05-28 09:23
that apk is working fine here

**Comment by Ockaie** [comment] 2017-05-28 09:27
same here

**Comment by MichelTenVoorde** [comment] 2017-05-28 09:32
Works just fine here too.

**Comment by th3an7** [comment] 2017-05-28 09:32
OK, will release newly updated apk to repo then :)

Thanks everyone for helping :D

**Comment by th3an7** [comment] 2017-05-28 09:34
BTW: Does this module displays notification all the time or only when YT is in background?

**Comment by Ockaie** [comment] 2017-05-28 09:41
All the time. However, when I close the notification while I'm in the YT app it doesn't come back until I put YT in the background.

**Comment by th3an7** [comment] 2017-05-28 09:48
Here is small bonus - this one should show notification only when YT is in background :)
[BackgroundOnly.zip](https://github.com/pylerSM/YouTubeBackgroundPlayback/files/1034084/BackgroundOnly.zip)

**Comment by zvonimir007** [comment] 2017-05-28 13:31
It's alive! Again! The module is working perfectly.. Thanks very much to th3an7 for hard work!

**Comment by Radioplayer1997** [comment] 2017-05-28 13:46
Thanks for getting it working on the latest version. BTW once I switched to the "notification always on" one, I found that it's very useful and I really like that simple add on.

**Comment by th3an7** [comment] 2017-05-28 13:52
Glad I could help :P

I'd also like to thanks everyone who reported it, posted logs and proposed changes :)
Enjoy YouTube in background :D

**Comment by DoomD95** [comment] 2017-05-28 16:22
Thank you! The app works. But when i installed the bonus app BackgroundOnly, the function disappeared. I had to reinstall to get back the function. Could u check it ? :D

**Comment by th3an7** [comment] 2017-05-28 16:26
Reinstall normal one or background only?

Try uninstalling module completely, then installing "bonus" one. Remember
to enable it in Xposed app and reboot after install!

**Comment by th3an7** [comment] 2017-05-28 16:34
Or if you could post logcat... Maybe I f***** up something again :P

**Comment by DoomD95** [comment] 2017-05-28 16:41
Haha. dont need to. After followed your steps, i got the app. I thought BO apk is an add on, so i installed it after installed the module. But doing a clean install is working. Thanks for your immediately support!

**Comment by th3an7** [comment] 2017-05-28 16:43
Oh, no problem :)
Glad you've fixed it :D

**Comment by osamamasimo11** [comment] 2017-05-28 23:46
It works perefectlly
Thank you

**Comment by rambomhtri** [comment] 2017-05-29 13:26
After the last update, it's working again perfectly. Thank you so much for fixing it quickly.
:1st_place_medal:

**Comment by th3an7** [comment] 2017-05-29 13:56
@rambomhtri not sure, but if your ROM supports Substratum themes, you could try preparing such theme for YouTube app :)

**Comment by rambomhtri** [comment] 2017-05-29 17:46
Thank you. My ROM is like 99% vanilla Android, although my carrier has done some minor modifications. In example, Xposed GravityBox works fine, and that module is meant to work mainly in vanilla Android. So, I guess my ROM is ready for that themes you say. How do they work? Where can I download them? Is there an official thread so I can dig more information?

**Comment by th3an7** [comment] 2017-05-29 18:27
Substratum theme engine has its own forum on XDA -
https://forum.xda-developers.com/apps/substratum

**Comment by th3an7** [comment] 2017-05-30 01:05
@rambomhtri Have you found your theme?
Got something for you... can you test it? :)

[test.zip](https://github.com/pylerSM/YouTubeBackgroundPlayback/files/1037008/test.zip)

**Comment by vorul** [comment] 2017-05-30 01:15
I'm having a similar issue. Youtube version 12.14.56

Upgrading to 2.02 broke background playback. Uninstalling and then reinstalling 2.01 made it works again.

**Comment by th3an7** [comment] 2017-05-30 01:19
@Vorul, 2.0.2 is made for YT 12.19.56+... It has no backwards
compatibility...
Stay on 2.0.1 or update your YT app :)

**Comment by rambomhtri** [comment] 2017-05-30 13:14
@th3an7 
Hallo my dear friend. No, unfortunately I couldn't manage to understand how Substratum works, it seems a little complicated. I installed it, went to settings and tried to apply some theme's but they were paid versions or there would be a message in Google Play saying my device is not compatible. Also I searched for How To videos in YouTube and I couldn't find a guide or tutorial explaining the basics: from start when you install the app to when you apply a little custom theme to a chosen app.

What's that zip?

**Comment by th3an7** [comment] 2017-05-30 13:27
@rambomhtri in a nutshell
- Download Substratum theme engine from Play Store (https://play.google.com/store/apps/details?id=projekt.substratum)
- Download zip I've posted earlier and install .apk from it
- After installing an app, open Substratum, you should see a list with installed themes
- Choose one, inside there, select app to theme (with a checkbox next to it)
- After selecting apps, click on paintbrush at the down right
- Select "Build & Enable", wait a while and you should be done :)

**Comment by rambomhtri** [comment] 2017-05-30 15:24
OK, I'm doing it right now.

By the way, if I understood well, Substratum is only a "color changer" of apps, it doesn't need to replace original Play Store apps, it's compatible with your module, it's compatible with future releases, etc... right?

But what would happen if YouTube app gets updated to 13.0 and includes new tabs and new UI?

Thank you for your time and help, really appreciated. 💯

**Comment by th3an7** [comment] 2017-05-30 15:45
Substratum is changing overlays so it does not modify anything in apk
files, it just lays it's layers on top of running apps (at least I think so)

It should work as long as you said - if they change something like colors
of the background, add a new tab or something like that, the theme also
needs to be updated...

**Comment by rambomhtri** [comment] 2017-05-30 16:36
OK, well, wow, wooow, WOOHOOW, what the hell, that's what I've been looking for, literally, 6 years. Amazing, actually amazing, truly amazing, amazingly amazing. I can't stop laughing, every single thing is blacked out, comments, all screens.

1. First, how did you do that? Hahaha, black magic, literally, hahaha.
2. I asked that first question to know if I would be able to customize a little bit those layers, in example: since my screen is not AMOLED (sad but true), I'd rather use a dark grey for general background color, and if it's possible different tones of grey separating sections like video title and description from suggested videos, comments from suggested videos, etc... Is it simple to do it or you need to know some programming? How much can you fine tune those colors?
3. I recently made a PayPal account (still don't know how to use it though, I'm in process of learning). When I'm ready, I'd love to buy you a beer or two for your background module and for this amazing tool and tutorial.

Thank you! :)

**Comment by th3an7** [comment] 2017-05-30 16:44
1. I've just used a tutorial from substratum github page - https://github.com/substratum/template :D
   There is also a video on XDA YT channel - https://www.youtube.com/watch?v=gNDKhBO3q-E
2. I could take a look and change something... hit me up on Hangout or something so we can talk about changes (don't want to spam it more here at it is already :P)

**Comment by Nintendragon** [comment] 2017-05-31 09:56
It's still not working for me, I thought the package I'll update itself? or do I need to manually install it?

**Comment by th3an7** [comment] 2017-05-31 10:13
Update the module to 2.0.2 - it should work

**Comment by Nintendragon** [comment] 2017-05-31 10:14
oh yeah. but 2.0.2 is not on xposed(?) 
I just installe it manually now.

**Comment by nuxbag** [comment] 2017-06-02 18:13
I have 2.0.2 installed and it doesn't work on some vids, and the slider or player controls play/paues etc  doesn't come up after tapping the screen sometimes.  only on some vids if i turn off the screen it stops playing and says There was a problem while playing Playback ID ib6hf7xyf_xy0qs

**Comment by Criptics** [comment] 2017-06-06 14:54
Works fine with the 2.0.2

**Comment by Shukaro** [comment] 2017-06-09 18:15
Does not work for me, YouTube 12.19.56, this 2.0.2, OS 6.0.1, phone nexus 5

**Closed** 2017-12-07 11:14 UTC
