### ISSUE TITLE
Persistent notification

### ISSUE THREAD

**Issue by andreasy73** [pylerSM/YouTubeBackgroundPlayback#148] opened 2016-05-03 18:12 UTC
Many times when I open a YouTube video, especially from the Facebook app (if it matters) it stays in notification and there is no way I can remove it. Pushing x just does nothing.

**Comment by zimlokks** [comment] 2016-05-09 19:40
Force closing the app fixes this issue. The issue is that YouTube is killed because of ram issues but the notification can't be swiped away, and the X can't kill a dead app.

**Closed** 2017-12-07 11:15 UTC
