### ISSUE TITLE
Does it work with the latest version?(12.47.58)

### ISSUE THREAD

**Issue by bestmjh47** [pylerSM/YouTubeBackgroundPlayback#353] opened 2017-12-18 12:02 UTC
It seems that this module doesn't work for the latest youtube version even after your update. 
I'm running youtube on Android 4.4 and according to apkmirror, there are some variants (for 4.1+,for 5.0+ etc..), so I think I'm currently using youtube which was built for kitkat, not lollipop-compatible version. Could it be a reason which hindered your module working on my device?

**Comment by bestmjh47** [comment] 2017-12-18 15:36
Thanks. Works perfectly fine now.

**Comment by Prolution** [comment] 2017-12-18 15:51
Confirmation: Module version 2.0.4 doesn't work with the latest YouTube app 12.47.58. I'm based on Android 7.1 (MIUI 9).

**Comment by th3an7** [comment] 2017-12-18 16:02
Ok... I found where is the problem now...

Code for 4.1+ and 5.0+ versions are different now - before, classes were named the same for both Android versions. Now, the naming is changed and the module is working either for 4.1+ or for 5.0+ and not at the same time...

The temporary solution would be to build the module for 4.1+ and 5.0+ YT apps separately so it would work for those versions...

**Comment by Kronopt** [comment] 2017-12-18 16:09
Can't you just have a json for each version here on the repo and check the version running on the device before downloading?

**Comment by th3an7** [comment] 2017-12-18 16:29
@bestmjh47 @Prolution @Kronopt can you please test [THIS](https://drive.google.com/file/d/19kpW0yzwASmST7c0cQUeLknKQIGA7kJn/view?usp=sharing) one?

If you're getting errors when installing it, uninstall the old one and try again

**Comment by sersimovi** [comment] 2017-12-18 16:38
Tested the apk on android 7.0, didn't work

**Comment by th3an7** [comment] 2017-12-18 16:48
@sersimovi can you check xposed log and/or logcat for any errors connected with module?

**Comment by sersimovi** [comment] 2017-12-18 16:53
12-18 16:34:30.288 I/Xposed  ( 3231): -----------------
12-18 16:34:30.288 I/Xposed  ( 3231): Starting Xposed version 89, compiled for SDK 24
12-18 16:34:30.288 I/Xposed  ( 3231): Device: SM-N920S (samsung), Android version 7.0 (SDK 24)
12-18 16:34:30.288 I/Xposed  ( 3231): ROM: NRD90M.N920SKSU2DQH2
12-18 16:34:30.288 I/Xposed  ( 3231): Build fingerprint: samsung/noblelteskt/noblelteskt:7.0/NRD90M/N920SKSU2DQH2:user/release-keys
12-18 16:34:30.288 I/Xposed  ( 3231): Platform: arm64-v8a, 64-bit binary, system server: yes
12-18 16:34:30.288 I/Xposed  ( 3231): SELinux enabled: yes, enforcing: yes
12-18 16:34:30.332 I/Xposed  ( 3231): -----------------
12-18 16:34:30.333 I/Xposed  ( 3231): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
12-18 16:34:32.373 I/Xposed  ( 3231): Detected ART runtime
12-18 16:34:32.389 I/Xposed  ( 3231): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
12-18 16:34:32.726 I/Xposed  ( 3231): Loading modules from /data/app/com.ryansteckler.nlpunbounce-1/base.apk
12-18 16:34:32.748 I/Xposed  ( 3231):   Loading class com.ryansteckler.nlpunbounce.hooks.Wakelocks
12-18 16:34:32.756 I/Xposed  ( 3231): Loading modules from /data/app/tw.fatminmin.xposed.minminguard-1/base.apk
12-18 16:34:32.916 I/Xposed  ( 3231):   Loading class tw.fatminmin.xposed.minminguard.Main
12-18 16:34:32.999 I/Xposed  ( 3231): Loading modules from /data/app/com.suyashsrijan.forcedoze-1/base.apk
12-18 16:34:33.172 I/Xposed  ( 3231):   Loading class com.suyashsrijan.forcedoze.XposedModule
12-18 16:34:33.179 I/Xposed  ( 3231): Loading modules from /data/app/de.defim.apk.bootmanager-1/base.apk
12-18 16:34:33.219 I/Xposed  ( 3231):   Loading class de.defim.apk.bootmanager.Xposed
12-18 16:34:33.228 I/Xposed  ( 3231):     [BootManager] initialized
12-18 16:34:33.228 I/Xposed  ( 3231): Loading modules from /data/app/ma.wanam.youtubeadaway-2/base.apk
12-18 16:34:33.238 I/Xposed  ( 3231):   Loading class ma.wanam.youtubeadaway.Xposed
12-18 16:34:33.238 I/Xposed  ( 3231):   Loading class ma.wanam.youtubeadaway.ResXposed
12-18 16:34:33.238 I/Xposed  ( 3231): Loading modules from /data/app/com.pyler.youtubebackgroundplayback-1/base.apk
12-18 16:34:33.250 I/Xposed  ( 3231):   Loading class com.pyler.youtubebackgroundplayback.YouTubeBackgroundPlayback
12-18 16:34:39.662 I/Xposed  ( 3232): -----------------
12-18 16:34:39.662 I/Xposed  ( 3232): Starting Xposed version 89, compiled for SDK 24
12-18 16:34:39.662 I/Xposed  ( 3232): Device: SM-N920S (samsung), Android version 7.0 (SDK 24)
12-18 16:34:39.662 I/Xposed  ( 3232): ROM: NRD90M.N920SKSU2DQH2
12-18 16:34:39.662 I/Xposed  ( 3232): Build fingerprint: samsung/noblelteskt/noblelteskt:7.0/NRD90M/N920SKSU2DQH2:user/release-keys
12-18 16:34:39.662 I/Xposed  ( 3232): Platform: arm64-v8a, 32-bit binary, system server: no
12-18 16:34:39.662 I/Xposed  ( 3232): SELinux enabled: yes, enforcing: yes
12-18 16:34:39.665 I/Xposed  ( 3232): -----------------
12-18 16:34:39.665 I/Xposed  ( 3232): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
12-18 16:34:40.585 I/Xposed  ( 3232): Detected ART runtime
12-18 16:34:40.600 I/Xposed  ( 3232): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
12-18 16:34:40.869 I/Xposed  ( 3232): Loading modules from /data/app/com.ryansteckler.nlpunbounce-1/base.apk
12-18 16:34:40.882 I/Xposed  ( 3232):   Loading class com.ryansteckler.nlpunbounce.hooks.Wakelocks
12-18 16:34:40.887 I/Xposed  ( 3232): Loading modules from /data/app/tw.fatminmin.xposed.minminguard-1/base.apk
12-18 16:34:41.041 I/Xposed  ( 3232):   Loading class tw.fatminmin.xposed.minminguard.Main
12-18 16:34:41.106 I/Xposed  ( 3232): Loading modules from /data/app/com.suyashsrijan.forcedoze-1/base.apk
12-18 16:34:41.261 I/Xposed  ( 3232):   Loading class com.suyashsrijan.forcedoze.XposedModule
12-18 16:34:41.268 I/Xposed  ( 3232): Loading modules from /data/app/de.defim.apk.bootmanager-1/base.apk
12-18 16:34:41.301 I/Xposed  ( 3232):   Loading class de.defim.apk.bootmanager.Xposed
12-18 16:34:41.310 I/Xposed  ( 3232):     [BootManager] initialized
12-18 16:34:41.310 I/Xposed  ( 3232): Loading modules from /data/app/ma.wanam.youtubeadaway-2/base.apk
12-18 16:34:41.320 I/Xposed  ( 3232):   Loading class ma.wanam.youtubeadaway.Xposed
12-18 16:34:41.320 I/Xposed  ( 3232):   Loading class ma.wanam.youtubeadaway.ResXposed
12-18 16:34:41.320 I/Xposed  ( 3232): Loading modules from /data/app/com.pyler.youtubebackgroundplayback-1/base.apk
12-18 16:34:41.461 I/Xposed  ( 3232):   Loading class com.pyler.youtubebackgroundplayback.YouTubeBackgroundPlayback
12-18 16:34:42.997 I/Xposed  ( 3785): ForceDozeXposed: usePermanentDoze: false, useXposedSensorWorkaround: false, serviceEnabled: false
12-18 16:34:43.006 I/Xposed  ( 3785): Amplify: Version 4.0.1
12-18 16:34:43.006 I/Xposed  ( 3785): Amplify: Attempting 19to21 AlarmHook
12-18 16:34:43.009 I/Xposed  ( 3785): Amplify: Successful 19to21 AlarmHook
12-18 16:34:43.009 I/Xposed  ( 3785): Amplify: Attempting 21 WakeLockHook
12-18 16:34:43.014 I/Xposed  ( 3785): Amplify: Successful 21 WakeLockHook
12-18 16:34:43.014 I/Xposed  ( 3785): Amplify: Attempting 23 ServiceHook
12-18 16:34:43.019 I/Xposed  ( 3785): Amplify: Successful 23 ServiceHook
12-18 16:34:55.156 I/Xposed  ( 3785): Amplify: XposedReceiver has been successfully installed.
12-18 16:36:22.377 I/Xposed  (10640): YouTube: com.google.android.youtube 12.47.58 loaded!
12-18 16:36:23.533 I/Xposed  (10640): YouTube AdAway: Successfully hooked ads DB zep
12-18 16:36:24.355 I/Xposed  (10640): YouTube AdAway: Successfully hooked ads wrapper 
12-18 16:36:26.876 I/Xposed  (10640): YouTube AdAway: Successfully hooked ads fetchers
12-18 16:49:16.113 I/Xposed  ( 3785): Amplify: Allowing Wakelock RILJ0.  Max Interval: 800000 Time since last granted: 894871
12-18 16:49:42.521 I/Xposed  ( 3785): Amplify: Allowing Wakelock NetworkStats.  Max Interval: 800000 Time since last granted: 921280

**Comment by th3an7** [comment] 2017-12-18 17:06
@sersimovi can you upload your YT .apk? The log doesn't show any errors - only that hooks were loaded...

**Comment by man0usos** [comment] 2017-12-18 17:27
@the3an7 the module was working perfectly for me while on 12.47.58, but today suddenly it stopped working, even though the youtube app got no update... I tried reinstalling and everything, still does not work. I'm on Android 6.0.1.
I think this is pretty weird.

**Comment by sersimovi** [comment] 2017-12-18 17:27
I'm on my phone right now and I don't see the option to upload an apk. It's the latest version from the playstore tho. I reinstalled YouTube and still anything.

**Comment by sersimovi** [comment] 2017-12-18 17:28
I had the same scenario as Manousos

**Comment by panyuhang93** [comment] 2017-12-18 17:35
Me too

**Comment by th3an7** [comment] 2017-12-18 17:36
@man0usos yes, I know that... I've changed hooks to test something - seems like it now works for YT Android 4.1+...

If I change it back, it will stop working for 4.1+ and will work again for 5.0+ like it was before...

As I wrote before, there was a change sometime ago (didn't even know about that tbh) an now classes in  YT app for 4.1+ and 5.0+ are different.

The easiest fix would be to make 2 separate module for YT made for 4.1+ and 5.0+ - I thought about just updating .json file with hooks for both versions, but apparently it doesn't work like that (according to reports earlier)...

Someone needs to either think of a fix and propose commit to .jar/.json or just make 2 versions of module...

**Comment by th3an7** [comment] 2017-12-18 17:40
If that module .apk posted earlier does't work for anyone, then I'll just build modules for both 4.1+ and 5.0+ separately

**Comment by bestmjh47** [comment] 2017-12-18 17:43
I think this option would be considered although this surely needs some code amendment.

1.  Detect Android version(or SDK version through getprop command).
2. According to getprop-ed OS version, download appropriate hook.

But as you proposed, just building and maintaing seperate modules for each OS would be nice. Either way, users except using Android 5.0+ have to reinstall their module.

**Comment by bestmjh47** [comment] 2017-12-18 17:54
Which option would you choose?
For your sake, cloning previous project and just changing package name and hook will be convenient to you than adding some detecting features..

**Comment by th3an7** [comment] 2017-12-18 17:55
This one should work for android 4.1 - please test it :)

[DOWNLOAD](https://drive.google.com/file/d/1TgfEVRczbhezLcJO6qkofQxcZ5PH81yX/view?usp=sharing)

**Comment by bestmjh47** [comment] 2017-12-18 17:56
Thanks. I'll go for it right away.

**Comment by bestmjh47** [comment] 2017-12-18 18:00
Umm.. The Latest Avast says it's a kind of virus.. Detection name: APK:CloudRep [Susp]

**Comment by panyuhang93** [comment] 2017-12-18 18:01
@man0usos @sersimovi update to xposed v89?

**Comment by th3an7** [comment] 2017-12-18 18:01
@bestmjh47 that's weird... it's exactly the same as the previous one but with changed link to .json

I think it's just false positive as it hooks to other app...

**Comment by sersimovi** [comment] 2017-12-18 18:02
@panyuhang93 already using it

**Comment by bestmjh47** [comment] 2017-12-18 18:04
Anyway, It works fine now. Tested on Youtube for Android 4.1+.
Thanks a lot.

**Comment by Zralle** [comment] 2017-12-18 18:04
Not working on android 7.0.1. Send the other apk and I will test it :)

**Comment by bestmjh47** [comment] 2017-12-18 18:05
@Zralle th3an7 uploaded apk for those who use YT built for Android 4.1+.

**Comment by bestmjh47** [comment] 2017-12-18 18:08
BTW, Is English your mother tongue? I think you're very good at English... I envy you..!

**Comment by th3an7** [comment] 2017-12-18 18:11
@Zralle you don't need to install anything... if it worked before (ex. yesterday or so), then you don't need to change anything - it will magically work again...

But if for some reason, you've already installed new one, [THIS](https://drive.google.com/file/d/0B8j7vCsf6RXcUGdQSzdwV1ZWNzA/view?usp=sharing) one should work...

@bestmjh47 if you're talking about me, no - it's not - I'm Polish :D 
But thanks :P

**Comment by Zralle** [comment] 2017-12-18 18:16
today I installed xposed update 89 and after that it didn't work... Yes, I did force stop app and reboot few times. (last time 30 minutes before)
I didn't install new version.

**Comment by sersimovi** [comment] 2017-12-18 18:18
@zralle I can confirm it's not Becuase of that. I had v80 when it stopped working. Updated to 89 to try if it'd fix it but nothing

**Comment by th3an7** [comment] 2017-12-18 18:26
@Zralle have you enabled the module after updating framework?

Also, after enabling it, you need to reboot

**Comment by th3an7** [comment] 2017-12-18 18:29
@sersimovi was it working before?
Force stop YT/reboot phone...

Also, which module version are you using right now?

**Comment by Zralle** [comment] 2017-12-18 18:33
yeah I checked all that.
I use app that you link in one post in other issue.

**Comment by th3an7** [comment] 2017-12-18 18:34
@Zralle that's weird...

As always - check xposed log/logcat for any errors

**Comment by Zralle** [comment] 2017-12-18 18:44
no errors.

Should I try reinstalling apk?

**Comment by th3an7** [comment] 2017-12-18 18:45
yeah, sure... don't forget to re-enable it :)

**Comment by Zralle** [comment] 2017-12-18 18:46
1 min

**Comment by Zralle** [comment] 2017-12-18 18:53
Working now. Don't know what I did wrong last time. I checked all steps :/

**Comment by th3an7** [comment] 2017-12-18 18:54
No problem @Zralle - glad it works now :D

I guess I'll close this issue... If anyone have any problems with this one yet, just reopen it :P

**Closed by th3an7** 2017-12-18 18:54 UTC

**Comment by sersimovi** [comment] 2017-12-18 21:38
Still not working for me. I'm on nougat 7.0, exposed v89 and using the 2.0.5 YBP version the apk that you uploaded. And like i said i'm using the last youtube of version 12.47.58, i reinstalled the module, youtube, rebooted, force stop... nothing worked

**Comment by th3an7** [comment] 2017-12-18 21:59
> I'm on nougat 7.0, exposed v89 and using the 2.0.5 YBP version

There's your problem... try the one from https://github.com/pylerSM/YouTubeBackgroundPlayback/issues/336 or https://github.com/pylerSM/YouTubeBackgroundPlayback/issues/353#issuecomment-352511576 (they are the same)

Was it working before?

**Comment by sersimovi** [comment] 2017-12-18 22:14
Okay solved, I wasn't using the apk on #353. Thanks
