### ISSUE TITLE
Youtube 10.37.58 not working

### ISSUE THREAD

**Issue by MayurAgarkar** [pylerSM/YouTubeBackgroundPlayback#72] opened 2015-09-29 15:25 UTC
Just updated to latest version 1.6.0
And youtube version 10.37.58 doesnt seem to be working. Just letting you know. :)
I wish i coukd gather sime debug log to give more info on this.

**Comment by pylerSM** [comment] 2015-09-29 20:36
I have it and it works. Did you enable it in Xposed Installer & reboot your device?

**Comment by Taknok** [comment] 2015-09-30 19:47
After 2 reboot it work for me : 1st reboot to install the module, then open the installer -> module and check the app ; 2nd reboot and it's ok !

**Comment by esgie** [comment] 2015-10-01 13:34
You can check the module in the Xposed Installer instantly after installing. So one reboot is required in total :)

**Comment by thirtythreeforty** [comment] 2015-10-02 07:22
I have the same issue. Same versions of both apps on CM12.1 M1.

Here's a (filtered) logcat:

```
10-02 02:20:22.590 I/ActivityManager( 2350): Killing 5271:com.google.android.youtube/u0a116 (adj 9): remove task
10-02 02:20:22.655 I/WindowState( 2350): WIN DEATH: Window{f584786 u0 com.google.android.youtube/com.google.android.apps.youtube.app.WatchWhileActivity}
10-02 02:20:27.295 I/Timeline( 2990): Timeline: Activity_launch_request id:com.google.android.youtube time:425760
10-02 02:20:27.296 I/ActivityManager( 2350): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.google.android.youtube/.app.honeycomb.Shell$HomeActivity (has extras)} from uid 10016 on display 0
10-02 02:20:27.317 V/WindowManager( 2350): addAppToken: AppWindowToken{225e2c74 token=Token{3641ac47 ActivityRecord{2ed4cb86 u0 com.google.android.youtube/.app.honeycomb.Shell$HomeActivity t11043}}} to stack=1 task=11043 at 0
10-02 02:20:27.408 V/WindowManager( 2350): Adding window Window{242d96a u0 Starting com.google.android.youtube} at 11 of 17 (after Window{3f91a48c u0 com.nolanlawson.logcat/com.nolanlawson.logcat.LogcatActivity})
10-02 02:20:27.452 I/ActivityManager( 2350): Start proc 11527:com.google.android.youtube/u0a116 for activity com.google.android.youtube/.app.honeycomb.Shell$HomeActivity
10-02 02:20:27.737 E/YouTube MDX(11527): Bogus value in shared preferences for key MdxServerSelection value , returning default value.
10-02 02:20:27.868 I/dex2oat (11562): /system/bin/dex2oat --runtime-arg -classpath --runtime-arg /system/framework/XposedBridge.jar --instruction-set=arm --instruction-set-features=default --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --dex-file=/data/data/com.google.android.youtube/cache/ads2030829230.jar --oat-fd=48 --oat-location=/data/data/com.google.android.youtube/cache/ads2030829230.dex --runtime-arg -Xms64m --runtime-arg -Xmx512m
10-02 02:20:27.983 I/Timeline(11527): Timeline: Activity_launch_request id:com.google.android.youtube time:426448
10-02 02:20:27.983 I/ActivityManager( 2350): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x4000000 cmp=com.google.android.youtube/com.google.android.apps.youtube.app.WatchWhileActivity (has extras)} from uid 10116 on display 0
10-02 02:20:27.994 V/WindowManager( 2350): addAppToken: AppWindowToken{6448d79 token=Token{1dd28a40 ActivityRecord{2db0f1c3 u0 com.google.android.youtube/com.google.android.apps.youtube.app.WatchWhileActivity t11043}}} to stack=1 task=11043 at 1
10-02 02:20:27.994 V/WindowManager( 2350): Based on layer: Adding window Window{242d96a u0 Starting com.google.android.youtube} at 11 of 17
10-02 02:20:28.933 V/WindowManager( 2350): Adding window Window{1cdf2ecc u0 com.google.android.youtube/com.google.android.apps.youtube.app.WatchWhileActivity} at 11 of 18 (before Window{242d96a u0 Starting com.google.android.youtube})
10-02 02:20:29.061 E/YouTube (11527): (unknown) Media progress reported outside media playback: NEW
10-02 02:20:29.103 I/ActivityManager( 2350): Displayed com.google.android.youtube/com.google.android.apps.youtube.app.WatchWhileActivity: +1s31ms (total +1s680ms)
10-02 02:20:29.103 I/Timeline( 2350): Timeline: Activity_windows_visible id: ActivityRecord{2db0f1c3 u0 com.google.android.youtube/com.google.android.apps.youtube.app.WatchWhileActivity t11043} time:427568
10-02 02:20:29.162 E/YouTube (11527): (unknown) Media progress reported outside media playback: NEW
10-02 02:20:30.688 W/YouTube (11527): (unknown) In CsiAction [bbv], past event br_r can't be marked
10-02 02:20:30.688 W/YouTube (11527): (unknown) In CsiAction [bbv], past event ol can't be marked
10-02 02:20:31.629 W/YouTube (11527): apps.youtube.app.WatchWhileActivity.a:50629 In CsiAction [knk], past event pl_int can't be marked
10-02 02:20:32.479 V/WindowManager( 2350): Adding window Window{16e5b871 u0 SurfaceView} at 11 of 18 (before Window{1cdf2ecc u0 com.google.android.youtube/com.google.android.apps.youtube.app.WatchWhileActivity})
10-02 02:20:32.714 W/YouTube (11527): (unknown) CsiAction [knk] already ticked asiss. Ignored.
10-02 02:20:32.886 W/YouTube (11527): (unknown) CsiAction [knk] already ticked ari. Ignored.
10-02 02:20:32.886 W/YouTube (11527): (unknown) CsiAction [knk] already ticked vri. Ignored.
10-02 02:20:32.902 W/YouTube (11527): (unknown) CsiAction [knk] already ticked asisrh. Ignored.
10-02 02:20:32.979 W/YouTube (11527): (unknown) CsiAction [knk] already ticked asisfb. Ignored.
10-02 02:20:32.980 W/YouTube (11527): (unknown) CsiAction [knk] already ticked arrh. Ignored.
10-02 02:20:32.980 W/YouTube (11527): (unknown) CsiAction [knk] already ticked asisr. Ignored.
10-02 02:20:32.980 W/YouTube (11527): (unknown) CsiAction [knk] already ticked arfb. Ignored.
10-02 02:20:32.980 W/YouTube (11527): (unknown) CsiAction [knk] already ticked vsiss. Ignored.
10-02 02:20:32.981 W/YouTube (11527): (unknown) CsiAction [knk] already ticked vrrh. Ignored.
10-02 02:20:32.985 W/YouTube (11527): (unknown) CsiAction [knk] already ticked vrfb. Ignored.
10-02 02:20:32.986 W/YouTube (11527): (unknown) CsiAction [knk] already ticked ar40k. Ignored.
10-02 02:20:35.910 W/PackageManager( 2548): Failure retrieving resources for com.google.android.youtube: Resource ID #0x0
10-02 02:20:38.409 D/StatusBar( 2548): Clicked on button -1 for 0|com.google.android.youtube|2|null|10116
```

**Comment by pylerSM** [comment] 2015-10-10 14:18
And what's the problem? "Not working" is a very poor description of the issue.

Notification is not shown?

**Comment by thirtythreeforty** [comment] 2015-10-10 15:30
Whoops, good point, sorry.  The notification appears, but when the YouTube
app is closed, the video immediately stops playing and the Play/Pause
button on the notification becomes an exclamation point.

Touching the notification to bring YouTube back to the foreground causes
shows the error "There was a problem while playing.  Touch to retry." on
the video playback area.

**Comment by pylerSM** [comment] 2015-10-11 10:10
Aha, that was issue some time ago for not pure music videos so we had to restart playback after we got exception. We will check it.

**Comment by esgie** [comment] 2015-10-11 15:08
Are you sure that the bug is not caused by Youtube AdAway module?
Developer has released a buggy version yesterday morning which was causing some problems then released a fix in the evening.

**Comment by thirtythreeforty** [comment] 2015-10-11 15:36
Hmm, I am using AdAway.  I will try updating and/or disabling it.

**Comment by thirtythreeforty** [comment] 2015-10-11 18:13
After disabling the YouTube AdAway module, the problem persists.  That is, same issue with it both enabled and disabled.

**Comment by esgie** [comment] 2015-10-12 16:56
I have found out that I am experiencing the same issue since 10.40.xx update. But only on my CM12.1 mobile phone - everything still works on a Samsung KitKat tablet even with 10.40.xx!
I have also never experienced such a bug on 10.37 even on CM12.1! I am 100% sure.
The logcat shows some problem with 'resources'...
All of the above made me think... I wonder if the error isn't caused by using the YouTube app revision for different dpi than the device?
For example 10.40.xx has been out for 480dpi only as for now:
http://www.apkmirror.com/apk/google-inc/youtube/youtube-10-40-56-480dpi-android-4-0-3-5-1-1-android-apk-download/
480dpi version should contain high density resources so maybe that is why it does work on my qhd tablet and not on my fullhd mobile?
@thirtythreeforty 
Can you test 1.6.3 with 10.38 which has been released as an universal build (ie. for all dpis)?
http://www.apkmirror.com/apk/google-inc/youtube/youtube-10-38-58-android-apk-download/

**Comment by thirtythreeforty** [comment] 2015-10-12 17:03
I just tried v1.6.3 with both v10.38.58 and v10.40.56, and the same thing is happening with both versions.

It's interesting that 10.38.x was never deployed to my device; I was stuck on 10.37.58.

**Comment by esgie** [comment] 2015-10-12 17:20
In my case:
- 10.37.58(nodpi) is working great on both devices
- 10.38.58(nodpi) is working great on both devices
- 10.39.54(nodpi) is working great on both devices
- 10.39.54(480dpi) is working great on both devices (so it's probably not dpi revision issue...).
- 10.40.56(480dpi) is working on tablet and is not working on phone.

I wonder if the 10.40.56 YT app isn't buggy in some way itself for some screens/devices - it may be dump from Marshmalllow build for specific Nexus device only or something... I will be able to confirm that after a next update...

But I still do not experience ANY errors when using ANY 10.37-10.39 build on ANY of my devices.

**Comment by iHelp101** [comment] 2015-10-12 17:21
Esgie try calling the method that enables audio (Request audio permission from Android) via the first class. The method can be easily found because it uses execute or executor (Forgot which). I have no idea if it will help, but it is worth a shot.

**Comment by esgie** [comment] 2015-10-12 17:24
My build environment is "out" again at least since tomorrow...
I will build tomorrow and post here.
However I still CANNOT reproduce the issue for 10.37 - 10.39!!!

**Comment by esgie** [comment] 2015-10-13 09:00
I have added callMethod in the first hook with method names as following (for YouTubes 10.36 - 10.40):
[CODE]public static final String[] METHOD_1_2 = { "K", "L", "P", "Q", "Q" };[/CODE]
This ain't fixed my issues with playback using 10.40.xx on my mobile running CM12.1, The same YouTube app also stull runs well on KitKat tablet.
However it may provide a fix for your problems with previous versions.
@thirtythreeforty can you test this build? I have added the code that @iHelp101 was talking about.
Download link: https://userscloud.com/0sx3qly1m56k

**Comment by anonymous1337** [comment] 2015-10-14 20:34
I also need help with this. It simply wont work i downloaded xposed aand downloaded the latest version of YoutubeBackgroundPlayback. I rebooted like it told me to than i went to youtube opened a video and nothing showed no notificiation. Than i pressed the home button and it paused it please help.

**Comment by TeamFail** [comment] 2015-10-15 04:39
Hm, I seem to be having issues with 10.37.58 as well it seems, although it seems to be limited to only one device (That being the one I just got back from repair running SlimKat), which is absolutely strange, because when I had issues with this before, the latest YouTubeBackgroundPlayback version fixed all that.

It's not that it doesn't work at all, _some_ videos do play in the background (It seems to be almost at random), but other songs will produce loud clicks (Usually on app transitions or screen power on/off) or just a really quiet empty noise (Kinda like a cassette tape when there's no recording on it) when the screen is on at all. I've had the YouTube app crash, or even have SystemUI completely crash. I've gone as far as disabling all my other Xposed Modules (Including AdAway and GravityBox, as well as RootCloak), and it doesn't seem to fix that issue.

I'll try @esgie's test build and see if it works though, who knows what'll happen with this phone that's been nothing but surprises.

**Comment by thirtythreeforty** [comment] 2015-10-15 04:47
@esgie thanks for the test build.  Unfortunately, it does not help; it
exhibits the exact same behavior.

One odd thing that I have noticed (with the stable build) is that very
occasionally, a video will go to background successfully, with audio
playing and proper pause/skip controls.  However, jumping back to the movie
causes it to stop.  Sorry I can't be more specific, but perhaps it will
help.

**Comment by miladmaz12** [comment] 2015-10-15 04:51
@esgie 
https://github.com/pylerSM/YouTubeBackgroundPlayback/issues/76

**Comment by thirtythreeforty** [comment] 2015-10-15 04:51
@esgie my bad! Your test build does indeed work with YouTube v10.38.58; I had made the above comment with v10.40.  Switching back to the older app version works.

Glad you're on the right track -- or at least it seems like it.

**Comment by miladmaz12** [comment] 2015-10-15 04:54
@thirtythreeforty new thread - https://github.com/pylerSM/YouTubeBackgroundPlayback/issues/76

**Comment by miladmaz12** [comment] 2015-10-15 19:17
@esgie - The latest version of your app doesn't work in 10.40.58

I see the ! button

**Comment by iHelp101** [comment] 2015-10-15 20:06
Class 1: kys -> kyr
Class 2 also changed, but I have not found it yet.

**Closed** 2017-12-07 11:15 UTC
