### ISSUE TITLE
Support for YouTube 34 and 35

### ISSUE THREAD

**Issue by tomgacz** [pylerSM/YouTubeBackgroundPlayback#71] opened 2015-09-05 12:27 UTC
Please add support for YouTube versions 34 and 35.

**Comment by 6O4** [comment] 2015-09-12 07:37
Yes please!

**Comment by abhijeetramgir** [comment] 2015-09-12 21:53
Yes please

**Comment by 6O4** [comment] 2015-09-12 22:18
Lol

**Comment by martynbm** [comment] 2015-09-12 22:22
repo add

**Comment by riccardosimo** [comment] 2015-09-15 23:36
Yes please :(

**Comment by Queph** [comment] 2015-09-16 10:51
Yes please.I need it.

**Comment by Vagelis1608** [comment] 2015-09-20 21:15
And 10.37: https://www.apkmirror.com/apk/google-inc/youtube/youtube-10-37-56-android-apk-download/

**Comment by sjholland** [comment] 2015-09-22 13:16
Thank you for your continued updates

**Comment by Retrovers** [comment] 2015-09-24 20:47
Please update 😭

**Comment by krutarth8495** [comment] 2015-09-24 21:58
Yes! Please

**Comment by terrorist96** [comment] 2015-09-26 14:46
10.37.58?

**Comment by iHelp101** [comment] 2015-09-27 00:56
10.34.57 Support. Keep up the good work Esgie.

public static final String BACKGROUND_PLAYER_SERVICE = "com.google.android.libraries.youtube.player.decrepit.player.BackgroundPlayerService";
public static final String CLASS_ENABLE_BACKGROUND_PLAYBACK = "kfj";
public static final String METHOD_ENABLE_BACKGROUND_PLAYBACK = "B";
public static final String FIELD_PLAYBACK_CONTROL = "f";
public static final String METHOD_RESTART_PLAYBACK = "h";
public static final String FIELD_ENABLE_NOTIFICATION = "d";
public static final String METHOD_NEXT_TRACK = "e";
public static final String FIELD_TIME_MILLS = "a";
public static final String FIELD_LENGTH_MILLS = "b";

**Comment by iHelp101** [comment] 2015-09-27 01:17
10.35.53 Support

public static final String BACKGROUND_PLAYER_SERVICE = "com.google.android.libraries.youtube.player.decrepit.player.BackgroundPlayerService";
public static final String CLASS_ENABLE_BACKGROUND_PLAYBACK = "kfj";
public static final String METHOD_ENABLE_BACKGROUND_PLAYBACK = "B";
public static final String FIELD_PLAYBACK_CONTROL = "f";
public static final String METHOD_RESTART_PLAYBACK = "h";
public static final String FIELD_ENABLE_NOTIFICATION = "d";
public static final String METHOD_NEXT_TRACK = "e";
public static final String FIELD_TIME_MILLS = "a";
public static final String FIELD_LENGTH_MILLS = "b";

**Comment by iHelp101** [comment] 2015-09-27 01:23
10.36.52 Support

public static final String BACKGROUND_PLAYER_SERVICE = "com.google.android.libraries.youtube.player.decrepit.player.BackgroundPlayerService";
public static final String CLASS_ENABLE_BACKGROUND_PLAYBACK = "kxo";
public static final String METHOD_ENABLE_BACKGROUND_PLAYBACK = "B";
public static final String FIELD_PLAYBACK_CONTROL = "f";
public static final String METHOD_RESTART_PLAYBACK = "h";
public static final String FIELD_ENABLE_NOTIFICATION = "d";
public static final String METHOD_NEXT_TRACK = "e";
public static final String FIELD_TIME_MILLS = "a";
public static final String FIELD_LENGTH_MILLS = "b";

**Comment by esgie** [comment] 2015-09-27 01:32
Hey! Thanks for feedback.
Guess next build will come soon.

**Comment by iHelp101** [comment] 2015-09-27 01:45
10.37.56 Support

public static final String BACKGROUND_PLAYER_SERVICE = "com.google.android.libraries.youtube.player.decrepit.player.BackgroundPlayerService";
public static final String CLASS_ENABLE_BACKGROUND_PLAYBACK = "knb";
public static final String METHOD_ENABLE_BACKGROUND_PLAYBACK = "B";
public static final String FIELD_PLAYBACK_CONTROL = "f";
public static final String METHOD_RESTART_PLAYBACK = "h";
public static final String FIELD_ENABLE_NOTIFICATION = "d";
public static final String METHOD_NEXT_TRACK = "e";
public static final String FIELD_TIME_MILLS = "a";
public static final String FIELD_LENGTH_MILLS = "b";

**Comment by terrorist96** [comment] 2015-09-27 03:00
@iHelp101 will that work for 10.37.58 too? I can post apk if needed. Thanks.

**Comment by iHelp101** [comment] 2015-09-27 03:09
@terrorist96 Yes, for small releases (Where third decimal column only changes) Google very rarely changes hooks. I checked just to make sure and I didn't spot any changes.

**Comment by Icmer** [comment] 2015-09-27 03:24
Can someone post a new apk?

**Comment by iHelp101** [comment] 2015-09-27 03:32
@Icmer The module is currently maintained by Esgie. Esgie appears to live in Poland (5:30 AM currently) so have a little patience. I simply supplied Esgie with the needed hooks to get things working again. Esgie is a talented developer that I am sure will get the module updated as soon as he/she can.

**Comment by esgie** [comment] 2015-09-27 10:01
Guys.
I'll compile tomorrow since I do not have a computer at home atm.

**Comment by 6O4** [comment] 2015-09-27 10:11
https://play.google.com/store/apps/details?id=com.aide.ui&referrer=utm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_term%3Daide&pcampaignid=APPU_1_vsAHVt3nNML3aPfrhagI

**Comment by iHelp101** [comment] 2015-09-27 15:45
I apologize Esgie for not noticing this. I didn't notice that in 10.36.52 Google changed one of the methods. To enable notifications they original called the method D() which returns e.e (Boolean). 

Google however changed from checking with D() to directly using e.e to check if the notification is allowed. I will see how we can resolve this check change.

**Comment by pylerSM** [comment] 2015-09-27 17:00
I believe when I commented "show notification" thing, it still worked.

**Comment by pylerSM** [comment] 2015-09-27 17:01
And it is awesome that they are people ready for help! I will put your nick in Xposed repo page.

BTW, maybe you know... why playback starts from 0.00 when you go outside YT app?

**Comment by iHelp101** [comment] 2015-09-27 17:14
I will look into the playback restarting. I would guess you have to hunt down for the onResume method call that is done when the application resumes. I am currently visiting a family member in the hospital, so later today I will look into both issues (Playback restart and check change). 

The check change just means you can't rely on changing the method result anymore (D/B). You have to modify the boolean of e that is referenced from e as well (Class kwv I believe).

**Comment by pylerSM** [comment] 2015-09-27 17:30
I added you as "dev" of YBP in Xposed repo. http://repo.xposed.info/module/com.pyler.youtubebackgroundplayback.

I think about creating "signing key" just for this module, so me, esgie or you can update it without breaking module signature.

**Comment by pylerSM** [comment] 2015-09-27 17:30
We need to convert this project for Android Studio, thought.

**Comment by esgie** [comment] 2015-09-27 17:31
I'll build tomorrow morning.
27 wrz 2015 19:30 "pyler" <notifications@github.com> napisał(a):

**Comment by pylerSM** [comment] 2015-09-27 17:35
iHelp101, I added you also as contributor in this project, so you can touch code whenever you want!.

I am really happy that everytime we have a crisis in a community/some project, somebody arrives and solves the problem.

**Comment by pylerSM** [comment] 2015-09-27 17:38
"The check change just means you can't rely on changing the method result anymore (D/B). You have to modify the boolean of e that is referenced from e as well (Class kwv I believe). "

I believe we can just use

´´´
Object o = (Object) XposedHelpers.getObjectField(
						param.thisObject, "e");
XposedHelpers.setBooleanField(o, "e", true);

´´´

**Comment by iHelp101** [comment] 2015-09-27 17:43
I will add the updated 10.36.52+ fix later today to this issue report. I appreciate the addition as a contributor. I will let Esgie format the code as he/she pleases. I know everyone has their own coding style, so I don't want to disrupt the main code structure.

**Comment by iHelp101** [comment] 2015-09-27 17:44
I see you found the fix. I will look into the playback issue and maybe also the multi-tasking issue as well.

**Comment by tomgacz** [comment] 2015-09-27 17:49
thanks creators for looking here and fixing issues :)

**Comment by pylerSM** [comment] 2015-09-27 17:53
On my PC I have Eclipse, just on my laptop I have Android Studio. Importing "eclipse" project makes it somehow unbuildable so esgie, if you can, please make it ready for AS. Thanks

**Comment by pylerSM** [comment] 2015-09-27 17:58
You can push your fix(es) to repo, I believe esgie runs "code formatting/refactoring" before build and push (I do) :)

**Comment by iHelp101** [comment] 2015-09-27 20:00
The code below causes an issue. It makes the text "Audio unavailable" appears instead of allowing the video to play. Also the method D needs changed to K since D is never called anymore.

Object o = (Object) XposedHelpers.getObjectField(param.thisObject, "e");
XposedHelpers.setBooleanField(o, "e", true);

**Comment by Retrovers** [comment] 2015-09-27 20:05
When the update is going to be published?

**Comment by iHelp101** [comment] 2015-09-27 21:16
I found the audio issue, but I am not sure how to fix it exactly. Below is a call that the app makes to get everything ready. L() request audio focus from the device. Since this flag is false at the moment the audio is never requested, which results in the "Audio unavailable" error.

if (obj != null && ((irq) (obj)).g() != null && ((irq) (obj)).g().c && !irq.b(((irq) (obj)).a))
            {
                flag = true;
            }
if (flag)
            {
                L();
                kwv kwv1 = e;
                kwv1.a(true);
                kwv1.b = null;
                b.p();
                if (h != null)
                {
                    h.A();
                }
                K();
                return new kmr(kms.a);
            }

**Comment by pylerSM** [comment] 2015-09-28 06:14
"Flag" is local variable, right? If so, it will be hard to do it.

**Comment by esgie** [comment] 2015-09-28 08:13
Hi guys.
At last I have some spare time.
Sorry for being so late but I did not have possibility to follow the thread at the weekend.
I am installing Android Studio atm etc. and I'll be back after I'll succeed in configuring it.

**Comment by esgie** [comment] 2015-09-28 12:58
So...

First, I would recommend to get the stuff working for youtube 10.34 (the first one after the "huge" update by Google), as it still does not seem to work at the moment. Then we may proceed with testing changes for 10.36 etc. etc.

I have created another branch here:
https://github.com/pylerSM/YouTubeBackgroundPlayback/tree/esgie-patch-1
1. I have deleted a code for yt<=10.33. It is useless for testing purposes and it can be merged again after the fix is found.
2. I am using values provided by @iHelp101 for 10.34 - 10.37.
3. No additional changes for 10.36+ (local boolean field value issue) merged yet.

This should work at least for youtube 10.34 and 10.35. However, it does not work. The notification is being shown but after dismissing to background the playback stops and "!" icon is shown in the notification instead of play/pause. So I guess some values are still wrong.
Can you check it?

For 10.36/10.37 nothing is shown and the module does not work - but I guess it's the right behavior as the fix is in progress.

Here is a compiled version of the above:
https://userscloud.com/uexryvqqyzec

**Comment by esgie** [comment] 2015-09-28 13:01
Btw I am compiling with AIDE.
Also I was trying to make Android Studio working but I have some major issues with Java installation grr, I am dealing with it, please be patient.

**Comment by iHelp101** [comment] 2015-09-28 13:10
I just tested 10.34 again and it is working. The notification never changes to a "!" icon for me when the device is turned off. Does your Xposed log reveal anything about a hook failing?

**Comment by iHelp101** [comment] 2015-09-28 13:20
Finishing test 10.35 as well and same result. Notification works correctly and advances along with restarts. When testing I hard code the hooks in with doing the version check. I will test your APK as well.

**Comment by esgie** [comment] 2015-09-28 13:25
Please test my apk.
"!" does not show after turning off the screen.
"!" does show after dismissing yt to background by home button.
(both 10.34 and 10.35)

**Comment by iHelp101** [comment] 2015-09-28 13:38
Tested your APK (My test version disabled) and everything is working fine for 10.34 and 10.35. Video linked below. No hints from your Xposed log regarding the ! icon?

https://www.youtube.com/watch?v=PSHZboZSkaA

**Comment by esgie** [comment] 2015-09-28 13:44
No info in logs. And still "!" after dismissing yt app to the background (after reboot).
Can you post your test version for 10.34 or 10.35 ?

**Comment by iHelp101** [comment] 2015-09-28 13:47
Sure, it is linked below. Are you saying you must dismiss the Youtube app and then reboot to get the icon? Or a reboot doesn't fix the issue?

https://mega.nz/#!U9k1zSDD!OjEXopqaSuBrRTmEMChnejVjqPj1Ht6GNj_or91lISQ

**Comment by esgie** [comment] 2015-09-28 13:49
No no, I just made the reboot to "refresh" all the apps and modules in memory. Nevermind.
To be exact, "!" shows up after starting the video in the background. If I dismiss the video which is turned off (not playing) at the moment the play icon is still there. It becomes "!" just after clicking it.
I am testing your build.

**Comment by esgie** [comment] 2015-09-28 13:57
That's exactly what we need at the very beginning.
Your version is not working for me too. "!" issue occurs.
Xposed logs shows only something about XGELSettings module which I use. Maybe it is somehow incompatibile with ytbp? Will test again in a minute on other device.

**Comment by iHelp101** [comment] 2015-09-28 14:09
I can't get the ! icon to appear, but I can confirm that when you press play in the background the video won't start.

**Comment by esgie** [comment] 2015-09-28 14:12
Second device: same result. "!" and no-go for background playback.
No info in the log.
Guess this is the primary issue to fix.

**Comment by tomgacz** [comment] 2015-09-28 14:39
yes, on versions 10.34 and 10.35 i have "!" when minimalize youtube, guys, what android do u have? maybe it's android versions issue? i have 5.1.1

**Comment by iHelp101** [comment] 2015-09-28 14:46
I tested another device and can confirm I am getting the "!" icon. I am trying to find the check that throws this error. I am wondering if it is audio related.

**Comment by iHelp101** [comment] 2015-09-28 14:49
I found the icon itself (ic_notification_error). Sadly the Youtube application doesn't appear to address this icon in anyway. Usually you would find a R$Drawables file, which I can't appear to find. 

![ic_notification_error](https://cloud.githubusercontent.com/assets/4932811/10138879/744d1bf8-65ce-11e5-9436-a2920a9237ed.png)

**Comment by esgie** [comment] 2015-09-28 15:04
METHOD_RESTART_PLAYBACK = "i"
fixes the "!"

**Comment by iHelp101** [comment] 2015-09-28 15:09
Great find. I believe that means everything works in 10.34 and 10.35.

**Comment by esgie** [comment] 2015-09-28 15:29
Not exactly.
First: we have still playback restart issue.
Second: I wonder if METHOD_NEXT_TRACK value is ok. I am changing it to ie. "d" and background playback still works.
I have tested the module with a playlist. When in background it does NOT jump to the next track after the playback finishes. It does jump to the next track after clicking next track button in notification, but not automatically. Hm..
@pylerSM: what was the original purpose of advanceNextTrack hook? Was it designed to jump between tracks when in background? Because I am not sure what to test... And finally, can you check what should be the proper values of METHOD_NEXT_TRACK for yt 10.34 or 10.35?

**Comment by iHelp101** [comment] 2015-09-28 15:38
I apologize for moving on to 10.36. I however found a fix to get audio and background play working (Allows multitasking), so I wanted to note it for the future. I will switch back to 10.34.

XposedHelpers.findAndHookMethod("knb", lpparam.classLoader, "J", new XC_MethodHook() {
                @Override
                protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
                    super.beforeHookedMethod(param);
                    XposedHelpers.callMethod(param.thisObject, "K");
                    Object o = getObjectField(param.thisObject, "f");
                    XposedHelpers.setBooleanField(o, "d", true);
                }
            });

            XposedHelpers.findAndHookMethod("iha", lpparam.classLoader, "a", new XC_MethodHook() {
                @Override
                protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
                    super.beforeHookedMethod(param);
                    XposedHelpers.setBooleanField(param.thisObject, "c", true);
                }
            });

**Comment by esgie** [comment] 2015-09-28 15:42
Nothing to aplogize for, we will return to the topic after fixing previous stuff for sure!
I am testing some advanceNextTrack modifications, will return as soon as finished.

**Comment by iHelp101** [comment] 2015-09-28 15:53
Esgie I think I found a fix (This fully enabled background play). Try adding that to your code for 10.34 just as a test. 

XposedHelpers.findAndHookMethod("hvv", lpparam.classLoader, "a", new XC_MethodHook() {
                @Override
                protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
                    super.beforeHookedMethod(param);
                    XposedHelpers.setBooleanField(param.thisObject, "c", true);
                }
            });

**Comment by esgie** [comment] 2015-09-28 16:06
Wow.
Your hook seems to change A LOT.
Investigating...

**Comment by esgie** [comment] 2015-09-28 16:25
O-m-g
You are the winner.
I have included your hook.
Also I have totally deleted enableNotification, advanceNextTrack and restartPlayback hook.
Works like a flaw. There is even no pause after dismissing to the background. (10.34 only as for now)
Guess you've just found something everyone's around was looking for.
Genius!
Now we have to find appropriate values for 10.35+

**Comment by iHelp101** [comment] 2015-09-28 16:44
This is the hook I found for 10.36 a few posts ago. I haven't tested 10.35, so please test it. 

10.35
XposedHelpers.findAndHookMethod("kwc", lpparam.classLoader, "a", new XC_MethodHook() {
            @Override
            protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
                super.beforeHookedMethod(param);
                XposedHelpers.setBooleanField(param.thisObject, "c", true);
            }
        });

10.36

XposedHelpers.findAndHookMethod("iha", lpparam.classLoader, "a", new XC_MethodHook() {
            @Override
            protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
                super.beforeHookedMethod(param);
                XposedHelpers.setBooleanField(param.thisObject, "c", true);
            }
        });

**Comment by esgie** [comment] 2015-09-28 16:47
...and "ihy" for 10.37.
I'm trying to make a build, please wait :)

**Comment by esgie** [comment] 2015-09-28 16:53
Ok. So:
10.34 and 10.35 works for me.
10.36 and 10.37 does not.
Any additional hooks that you did use in your code?

**Comment by iHelp101** [comment] 2015-09-28 16:57
Are you getting an error? These are the only hooks I used.

XposedHelpers.findAndHookMethod("knb", lpparam.classLoader, "J", new XC_MethodHook() {
            @Override
            protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
                super.beforeHookedMethod(param);
                XposedHelpers.callMethod(param.thisObject, "K");
                Object o = getObjectField(param.thisObject, "f");
                XposedHelpers.setBooleanField(o, "d", true);
            }
        });

        XposedHelpers.findAndHookMethod("iha", lpparam.classLoader, "a", new XC_MethodHook() {
            @Override
            protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
                super.beforeHookedMethod(param);
                XposedHelpers.setBooleanField(param.thisObject, "c", true);
            }
        });

**Comment by esgie** [comment] 2015-09-28 16:59
*by 10.36/10.37 "does not work" - I meant it does not even show a notification.
I did not include the first hook above. Testing.

**Comment by esgie** [comment] 2015-09-28 19:09
I confirm fully working with both your hooks on 10.37.

**Comment by iHelp101** [comment] 2015-09-28 19:16
To make it easy you can use knb as class_enable and JJ as the method to that class. That way no additionl arrays need added. Then you just use a version check to add the additional hooks we found today.

**Comment by iHelp101** [comment] 2015-09-28 19:17
I haven't check 10.37 since I am not home. I will look at it when home if you don't find it.

**Comment by esgie** [comment] 2015-09-28 19:27
No problem about knb and J. I mostly wonder about the part:

XposedHelpers.callMethod(param.thisObject, "K");
Object o = getObjectField(param.thisObject, "f");
XposedHelpers.setBooleanField(o, "d", true);

How did you obtain the names K f and d? Can you give me an example how did you obtain them from the source code so I'll be able to still maintain the module in the future on my own?

**Comment by iHelp101** [comment] 2015-09-28 19:47
K is a method in knb that handles sound. I am not sure if it is needed after hooking our new method. You can try if deleting it allows it to work. The way I found it is the only method that uses "execute". 

F is the object we use to get the class that handles the boolean we need to change. D is the boolean that we are changing. An easy way to find the needed object and boolean field is find the method where it states something similar to "if (f.d | v) { *Random code* K(); }".

**Comment by esgie** [comment] 2015-09-28 20:17
Yes yes I figured it out, thank you.
Another half an hour spent on figuring out that YouTube app started to use different versionCode than previously - for 10.36 it's 1076 (not 1036) and for 10.37 it's 1077.
Neverthless I have working universal build that is working for both 10.36 and 10.37 (and shall be easily maintainable in the future - at least until next "earthquake").
Last testing. I'll publish it here in no more than 15 min.

**Comment by esgie** [comment] 2015-09-28 20:28
https://userscloud.com/warlqq4i5m4m
Please test! Should work with BOTH yt 10.36 and 10.37.
Will not work with previous version (but who cares).

**Comment by Retrovers** [comment] 2015-09-28 20:41
Work on 10.37

**Comment by miladmaz12** [comment] 2015-09-28 20:43
Works in 10.37 for me

**Comment by esgie** [comment] 2015-09-28 20:48
Nice. More feedback well appreciated, so I've uploaded this build to xposed repo as an experimental version.
However, I am testing this right now and it seem to work like crazy!
It wouldn't be possible in any way without the help of @iHelp101 who did a great job.
Thank you so much!

PS. I'll sync the sources tomorrow as I am quite tired at the moment.

**Comment by iHelp101** [comment] 2015-09-28 20:56
Thanks for letting me work on the project Esgie. If you ever need help or have trouble with the hooks feel free to contact me on XDA (iHelp101). Keep up the great work.

**Comment by pylerSM** [comment] 2015-09-29 05:08
My god, you are magicians! :D

**Comment by esgie** [comment] 2015-09-29 08:19
Guys, did you experience any bugs?
Works like a charm for me.
Do you think it's a good idea to mark the new version as "stable"?

**Comment by SandPox** [comment] 2015-09-29 09:19
yes, working fine for me too

**Comment by 6O4** [comment] 2015-09-29 10:07
For me too. Thank you ;)

**Comment by pylerSM** [comment] 2015-09-29 10:51
if it is possible, try to simply comment what you did in the code :)

**Comment by esgie** [comment] 2015-09-29 11:00
The hooks are COMPLETELY rewritten - basing on iHelp101 wonderful finding for 10.36.xx here:
https://github.com/pylerSM/YouTubeBackgroundPlayback/issues/71#issuecomment-143803901
(he may be probably the best person to explain how do the hooks work exactly). I have found proper values for 10.37.xx and parametrized the whole stuff (by creating new arrays) just as it was before. 

That's probably all :) Hope Google will not change the structure of the code at least for a while.

**Comment by esgie** [comment] 2015-09-29 11:04
@pylerSM did you see it in action? I am personally amazed, it is really useful module now!!

**Comment by iHelp101** [comment] 2015-09-29 14:01
The additional hook simply helps us pass a check. I originally was looking for the "Audio unavailable" reference in the YouTube applications code. I finally found the string reference by using a JADx decompiler (Experimental). Once I knew where the string was I just needed to find why the check was failing. 

I saw a boolean needed to be true, so I did a test. Out of luck it solved the issue and fully enabled background play (Didn't even know this was a feature in the YouTube app). If my research is correct background play is a paid feature (Original code had it partially enabled). Google is not going to be happy that the module fully bypasses the check.

I would expect almost every update is going to attempt to disrupt the module from working. I wish you the best of luck and be sure to comply with Google if they ask you to quit development. In the end the module makes a paid feature ($10/Month) free, which Google may not be happy about.

**Comment by esgie** [comment] 2015-09-29 14:24
You have to know that this feature/service is not available at all in Europe (yet?).
Until then we have no other way of playing media in background via youtube.

**Comment by terrorist96** [comment] 2015-09-29 18:09
@iHelp101 paid feature? Where's the option to pay to enable it? I've never seen or heard of this.

**Comment by esgie** [comment] 2015-09-29 18:40
@terrorist96 
US only i guess.
AFAIR I recently read it's coming to Europe soon and also it will be unified with Google Music paid subscription or something.

**Comment by terrorist96** [comment] 2015-09-29 18:45
I'm in the US

**Comment by esgie** [comment] 2015-09-29 18:46
And do you have access to Youtube Music Key service?http://www.androidpolice.com/2015/09/26/youtubes-completely-ad-free-subscription-likely-to-launch-october-22nd-with-the-name-youtube-red/
It's one of its features.

**Comment by iHelp101** [comment] 2015-09-29 19:02
I have no idea if this feature is available currently in the US. I apologize for causing an issue with discussing this. I just wanted to give Esgie a friendly heads up to be careful.

**Comment by terrorist96** [comment] 2015-09-29 19:06
Interesting. Looks like it hasn't launched yet.

**Comment by esgie** [comment] 2015-09-29 19:14
Ok thread closed

**Closed by esgie** 2015-09-29 19:14 UTC

**Comment by 6O4** [comment] 2015-09-29 19:21
:(

**Comment by pylerSM** [comment] 2015-09-29 20:38
Yes, tested module, amazing.

Google haven't contacted me yet, so I don't think they will care about it now.
