### ISSUE TITLE
Not working with 11.04.56

### ISSUE THREAD

**Issue by manish4518** [pylerSM/YouTubeBackgroundPlayback#127] opened 2016-02-27 14:23 UTC
Youtube crashes on screen off.

**Comment by esgie** [comment] 2016-02-27 16:37
Which version of module are you using? 1.8.5?
Please also post xposed log.

pzdr
es
27 lut 2016 15:23 "manish4518" <notifications@github.com> napisał(a):

**Comment by manish4518** [comment] 2016-02-29 03:28
Thank you for your prompt reply.

Yes using 1.8.5

You can download xposed log from below link
https://www.dropbox.com/s/gk6ems1wewrie9k/xposed_error_20160229_085357.log?dl=0

**Comment by manish4518** [comment] 2016-03-03 04:23
Today updated to 1.8.6

Still same issue.

**Comment by esgie** [comment] 2016-03-03 14:56
According to the logs, our module is working perfectly.
Some third party module which package's name is:
com.phantom.onetapyoutubemodule.YoutubeMediaHook
is causing a crash.

**Comment by manish4518** [comment] 2016-03-06 03:56
I removed onetabyoutube module completely.

Also updated youtube adaway. Still same issue.

Attached xposed log at below link
https://www.dropbox.com/s/dmw2mipzwn0xqow/xposed_error_20160306_092215.log?dl=0

**Comment by iHelp101** [comment] 2016-03-06 04:13
@esgie I think it would be great if you added some outputs for the module. That way you can easily diagnosis issues. I terms of the issue with @manish4518 try disabling SecureSettings and see if the issue is resolved. Your log shows that SecureSettings appears to have a bad hook related to the lock screen service. I am wondering if it is interfering with something. 

try {
   findAndHookMethod(CLASS_1[i], loader, METHOD_1[i], new XC_MethodHook() {
            @Override
            protected void beforeHookedMethod(final MethodHookParam param) throws Throwable {
                setBooleanField(getObjectField(param.thisObject, FIELD_1[i]), SUBFIELD_1[i], true);
            }
   });
} catch (Throwable t) {
   XposedBridge.log("Background Hook Failed: " +t);
   XposedBridge.log("Background Class: "+CLASS_1[i]+";Background Method: " +METHOD_1[i]);
}

**Comment by manish4518** [comment] 2016-03-06 08:16
After disabling secure settings, one benefit is that now youtube is not crashing after screen off. Earlier it was crashing after screen off.

YET, on screen off I don't here youtube. It works normal as if YT backgroud is not installed.

**Comment by esgie** [comment] 2016-03-14 07:26
I will think about adding some outputs in the next release.
Thank you for solving the issue. Closing.

**Closed by esgie** 2016-03-14 07:26 UTC
