### ISSUE TITLE
YouTube 10.38.58 not working

### ISSUE THREAD

**Issue by GustavoWiesner** [pylerSM/YouTubeBackgroundPlayback#73] opened 2015-10-02 14:53 UTC
Hi guys, how are you? Excuse my poor English. Moments ago updated to version 10.38.58 YouTube and YouTube Background Playback does not work, try turning off, activating the module again and restarting the device and not worked.

**Comment by iHelp101** [comment] 2015-10-02 15:29
**Note For Esgie (Untested)**
Class 1: koj -> kqp
Class 1 Method: K -> O
Class 2: ihy -> ijx

**Comment by GustavoWiesner** [comment] 2015-10-02 17:49
Excuse my ignorance, but I do not understand what you want to explain.

**Comment by iHelp101** [comment] 2015-10-02 17:59
I apologize for the vague reply I made. These are the changes that were made in 10.38.58. Esgie will understand them and easily be able to test and release an update.

**Comment by GustavoWiesner** [comment] 2015-10-02 18:42
No problem, thank you very much for your reply.

**Comment by esgie** [comment] 2015-10-03 14:52
Hi.
Seems NOT working.
"Audio not responding" error (I have polish translation, not sure what is the original warning).
Used your values. Then checked myself - and they seem to be correct. So... did they change something again...? Seems yes.
PS: As far as I can see, the "K" method was public and now the "O" method (ie. METHOD_1_1) is private. May that be the cause?

**Comment by iHelp101** [comment] 2015-10-03 14:54
I don't believe making a method private prevents Xposed from hooking it. Give me a moment and I will test it myself to see what the error is. With the error we can of course track where the code fails.

**Comment by iHelp101** [comment] 2015-10-03 15:04
I just tested everything and it is working for me. Do you instantly get the "Audio not responding" error or do you do something specific to trigger it. Also I always just hard code the hooks when testing because it is less difficult to make mistakes. Using the code below with no issues.

            XposedHelpers.findAndHookMethod("kqp", lpparam.classLoader, "O", new XC_MethodHook() {
                @Override
                protected void afterHookedMethod(MethodHookParam param) throws Throwable {
                    super.afterHookedMethod(param);
                    Object o = XposedHelpers.getObjectField(param.thisObject, "e");
                    XposedHelpers.setBooleanField(o, "e", true);
                }
            });

            XposedHelpers.findAndHookMethod("ijx", lpparam.classLoader, "a", new XC_MethodHook() {
                @Override
                protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
                    super.beforeHookedMethod(param);
                    XposedHelpers.setBooleanField(param.thisObject, "c", true);
                }
            });

**Comment by esgie** [comment] 2015-10-03 16:37
I'm sorry, I have had just mistyped something in my build, it's probably because I have been building natively on Android using AIDE and I broke the screen in my 12" tablet two days ago so I have to compile... on my mobile phone. Which is crap :(
I'll try again in some spare time. Sorry again.

**Comment by miladmaz12** [comment] 2015-10-03 17:02
YT 10.59 has been released http://www.apkmirror.com/apk/google-inc/youtube/youtube-10-39-54-240dpi-android-apk-download/

**Comment by esgie** [comment] 2015-10-03 17:09
"kul", "P", "ink"
1.6.2 released with support for both yt 10.38.xx and 10.39.xx.

**Closed** 2015-10-06 16:56 UTC
