### ISSUE TITLE
General issue reports vol. 2

### ISSUE THREAD

**Issue by terrorist96** [pylerSM/YouTubeBackgroundPlayback#357] opened 2018-02-22 12:12 UTC
Been getting constant crashes in YouTube recently. Haven't tested without this module yet but thought I'd provide this log in case it helps.

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:309)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.ClassCastException: alyl cannot be cast to javax.net.ssl.HttpsURLConnection
	at com.pyler.youtubebackgroundplayback.YouTubeBackgroundPlayback$HooksDownloadTask.doInBackground(YouTubeBackgroundPlayback.java:266)
	at com.pyler.youtubebackgroundplayback.YouTubeBackgroundPlayback$HooksDownloadTask.doInBackground(YouTubeBackgroundPlayback.java:253)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more

```

**Comment by sigv** [comment] 2018-04-05 17:46
@th3an7 Mind rebuilding the APK?

**Comment by th3an7** [comment] 2018-04-05 18:00
Not at all @sigv ... will do it right away :D

**Comment by th3an7** [comment] 2018-04-05 21:47
Sorry it took me so long... f***** Android Studio trolled me for 3h straight with Gradle syncs errors...

# BUT HERE THEY ARE:

- ### [NEW 2.0.5 for Android 5.0+](https://drive.google.com/file/d/13v09sIiqWGbu7LLFjEopIpWqMjQR67q7/view?usp=sharing)

- ### [NEW 2.0.5 for Android 4.2+](https://drive.google.com/file/d/1bA0dLNni24gpo4YwsNFYRuvHTuAU3FAW/view?usp=sharing)

Also, if it doesn't want to install, report it so I'll make one change :P

**Comment by terrorist96** [comment] 2018-04-05 22:38
> What manufacturer and Android version is this?

Nexus 6p

> Are you running some other Xposed modules that do something with your networking?

Running YouTube AdAway too.
Also, I've since upgraded to a Note 8 without root/xposed, so I'm of no help in troubleshooting this further.

**Comment by sigv** [comment] 2018-04-05 22:55
Well, this change should deal with the issue for anyone else who might have experienced this. 🤷‍♂️
Thanks for reporting anyhow.

**Comment by sigv** [comment] 2018-04-05 22:56
Closing as this can be moved over to that big thread I think.

**Comment by sigv** [comment] 2018-04-05 22:57
@th3an7 ..or do you want to keep this ticket open and close that one?

**Comment by th3an7** [comment] 2018-04-05 23:00
Maybe we should leave this open and close #336 as it has 170 posts and it starts to lag when I open that issue :D

Also @sigv did you see my latest commits regarding gradle? Are they OK or it should be reverted?

**Comment by sigv** [comment] 2018-04-05 23:15
> did you see my latest commits regarding gradle? Are they OK or it should be reverted?

Pushed ff3629dd6b9474c6e5e49d1c94714192cf7474fe on top, but looks good.
Honestly was too lazy to look into it. Thanks! 👍

**Comment by Electricity2015** [comment] 2018-05-15 10:40
Hi,I have a question ,what to do to see the notification when I am in app, not just in background?
(Android 7)

**Comment by th3an7** [comment] 2018-05-15 10:57
Well @Electricity2015... I'm afraid nothing... It's controlled by YouTube app and not by module - the only one who can change that is Google...

But there was module version with changed hooks that showed notification all the time - I've stopped updating them as only few people knew about it - I could try updating it again and recompile new .apk for you to check if the method is still working :P

**Comment by th3an7** [comment] 2018-05-15 20:37
@Electricity2015 Forgot to ask one thing which might solve "not working at all" problem - which YT version are you using? I've modified that module so it "should" work with the latest 13.18.54 version...

If you're below it, grab updated apk from apkmirror and test that module again :P

**Comment by Electricity2015** [comment] 2018-05-15 22:31
Now it is working but still not when YouTube is opened

**Comment by sersimovi** [comment] 2018-05-17 08:29
Not working at all with the latest update.

**Comment by th3an7** [comment] 2018-05-17 20:59
@Electricity2015 Then I can't do anything - just roll back to previous version :P

@sersimovi I've updated the module for 13.18.55 - roll back to previous version (not that from 2 days ago) - it should work again…

**Comment by bestmjh47** [comment] 2018-05-19 15:16
After updating to the latest version of youtube, your module constantly crashes youtube. Tested on Android 6.0.1 and 7.0.2. After deactivating your module, the problem has gone but I couldn't get background musics anymore. Do you have any idea why this happens?

**Comment by Zralle** [comment] 2018-05-21 13:59
Same here... youtube keeps crashing... I've been using this module for a long time and it worked but since last month I think youtube crashes. I can get yt to work after clearing data but if I close it, it keeps crashing.

**Comment by Electricity2015** [comment] 2018-05-21 14:08
Uninstall ,download module again and install ,for me worked.

**Comment by sersimovi** [comment] 2018-05-21 14:37
Wow it worked my dude, thank you Electricity2015

**Comment by kurci2** [comment] 2018-05-25 12:42
Youtube Cakground Playback version 2.0.5. Android 8.1.0, Magisk 16.0, Xposed 90.2-beta3 systemless.
Youtube version 13.20.52.
Have reinstalled the module but it stopped working after update.
I hope it is possible to fix (again).
All the best!

**Comment by th3an7** [comment] 2018-05-25 12:48
@kurci2 13.20.52 is not yet added... I'll update module as soon as new YT .apk is available on apkmirror...

Alternatively you could upload it somewhere to make whole process a lot faster :)

**Comment by kurci2** [comment] 2018-05-25 12:55
@th3an7, tkank you for your reply. I did not know that you need the apk.
Here is the link of the Youtube 13.20.52 apk extracted from my phone - [Google Drive](https://drive.google.com/open?id=17nbQUuwFcOV8BblLb4gqDDi4oX7XamKu).
Hope it helps.

**Comment by th3an7** [comment] 2018-05-25 13:14
@kurci2 yes, thanks for that - I've updated hooks and the module should work again now - try force closing YT app and/or reboot your device

**Comment by kurci2** [comment] 2018-05-25 13:31
@th3an7, no problem and thank you.
I can confirm that the module works again, also thank you for updating your apk files.

**Comment by kurci2** [comment] 2018-05-30 14:20
Stopped working again on [Youtube 13.20.53](https://drive.google.com/open?id=1xA_yBt8DYbQj588UsY-0zbWNQxB1xZuC).
Do you think that it is a cat and mouse game and it is best to just disable automatic updates?

**Comment by quangtaiqn** [comment] 2018-06-21 03:41
The app does not work in the latest version of YouTube (13.23.59)
@th3an7

**Comment by kevinmustaqim** [comment] 2018-06-24 06:09
Version 2.0.5 for Android 5.0+ working well on YTv13.23.59

**Comment by truquete** [comment] 2018-06-30 08:30
is there any kind soul who could send me the module or a link? I am not familiar with building for android. Thanks

**Comment by kurci2** [comment] 2018-06-30 08:31
@truquete:
https://github.com/pylerSM/YouTubeBackgroundPlayback/issues/357#issuecomment-379087066

**Comment by th3an7** [comment] 2018-07-21 13:03
@sigv could you look at this?

```
07-21 01:44:27.047 20915 20915 E AndroidRuntime: FATAL EXCEPTION: main
07-21 01:44:27.047 20915 20915 E AndroidRuntime: Process: com.google.android.youtube, PID: 20915
07-21 01:44:27.047 20915 20915 E AndroidRuntime: java.lang.IllegalArgumentException: Cannot hook interfaces: public abstract boolean abyx.c()
07-21 01:44:27.047 20915 20915 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.hookMethod(XposedBridge.java:207)
07-21 01:44:27.047 20915 20915 E AndroidRuntime: 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:187)
07-21 01:44:27.047 20915 20915 E AndroidRuntime: 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:260)
07-21 01:44:27.047 20915 20915 E AndroidRuntime: 	at com.pyler.youtubebackgroundplayback.YouTubeBackgroundPlayback.hook(YouTubeBackgroundPlayback.java:263)
07-21 01:44:27.047 20915 20915 E AndroidRuntime: 	at com.pyler.youtubebackgroundplayback.YouTubeBackgroundPlayback.access$400(YouTubeBackgroundPlayback.java:41)
07-21 01:44:27.047 20915 20915 E AndroidRuntime: 	at com.pyler.youtubebackgroundplayback.YouTubeBackgroundPlayback$HooksDownloadTask.onPostExecute(YouTubeBackgroundPlayback.java:347)
07-21 01:44:27.047 20915 20915 E AndroidRuntime: 	at com.pyler.youtubebackgroundplayback.YouTubeBackgroundPlayback$HooksDownloadTask.onPostExecute(YouTubeBackgroundPlayback.java:274)
07-21 01:44:27.047 20915 20915 E AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:651)
07-21 01:44:27.047 20915 20915 E AndroidRuntime: 	at android.os.AsyncTask.access$500(AsyncTask.java:180)
07-21 01:44:27.047 20915 20915 E AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
07-21 01:44:27.047 20915 20915 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-21 01:44:27.047 20915 20915 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:152)
07-21 01:44:27.047 20915 20915 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5497)
07-21 01:44:27.047 20915 20915 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-21 01:44:27.047 20915 20915 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-21 01:44:27.047 20915 20915 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-21 01:44:27.047 20915 20915 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
```

Reported [HERE on XDA](https://forum.xda-developers.com/showpost.php?p=77130202&postcount=354) - the device is OnePlus 2 with systemless Xposed v89...

**Comment by man0usos** [comment] 2018-08-02 21:18
doesn't work with latest update (13.29.53)
:)

**Comment by man0usos** [comment] 2018-08-02 21:25
@th3an7 it "magically" started working again after messing around(reinstalling ytb app and module etc)  thanks.

**Comment by th3an7** [comment] 2018-08-02 21:32
@man0usos after every update of YT app, hooks are updated here so you don't have to install new module .apk everytime new YT gets released...

The one thing you need to do is to reboot your device or force close youtube app - this will force hooks to be downloaded - just make sure they are updated (there will be commit with supported YT version like this one https://github.com/pylerSM/YouTubeBackgroundPlayback/commit/bb3f3a7e2c323de8fe61d15fec4148ace446eb51)

**Comment by jabarel** [comment] 2018-10-02 22:41
@th3an7 the YouTube it's crashing....cannot open it can you check please I'm on oxygen os 5.1.6 Oreo with system less Xposed ....YouTube version 13.39.51 and module it's 2.0.5

**Comment by th3an7** [comment] 2018-10-02 22:48
@jabarel hmm... are you using adaway or something similar?
Check logcat and xposed logs for any errors...

**Comment by jabarel** [comment] 2018-10-03 04:56
> @jabarel hmm... are you using adaway or something similar?
> Check logcat and xposed logs for any errors...

i uninstall all modules.....seems the youtube adway crashing things and its not youtube play in background problem :D sorry thanks for your tips

**Comment by AuroraWright** [comment] 2018-10-20 13:11
13.41.53 is out on the store and it's not supported (as expected as 13.41.52 is the last update I guess, just letting you know)

**Comment by th3an7** [comment] 2018-10-20 13:33
@AuroraWright I know, and as I said already on XDA [HERE](https://forum.xda-developers.com/showpost.php?p=77924366&postcount=421) I think I, myself, will be switching to either weekly or 2 weeks hooks updates...

There were a lot of new YT app updates (new version every 3 days) + new beta updates (which I'll be skipping completely I guess)...

Since I am still the only one who's updating hooks, I don't have that much time and resources to sit here and update this repo every day...

Also I think lots of people switched to YouTube Vanced already and this module is not as popular and used as much as it was before


But if users still want this module to be updated, I'll try to maintain current state...
Let me know what you (and rest of users) think about it...

**Comment by AuroraWright** [comment] 2018-10-20 15:05
How do you update hooks? Is it manual (apktool/comparing versions etc) or with a script? And in the former case, is it something that can be feasibly automated?

**Comment by th3an7** [comment] 2018-10-20 15:31
I am doing everything manually - decompiling app, comparing with previous version and updating hooks based on that...

If you looks at previous version and compare it with the latest one, you'll see the classes haven't changed - only their place have been switched... This can be easly verified as HEX code of each one is basically the same (I think that's the fastest way to find the classes)...

It takes maximum of 5 minutes to find all the classes and update hooks here, but since the updates are released too frequently, skipping some of them would be OK as hooks files are getting bigger and bigger with each version - I would drop support for some super old versions but I don't know how old versions are still in use...

I will update hooks for 13.41.53 and the module should work again in ~1h (as classes are probably the same, we're just missing version number for .53)


I'll be observing further updates - if they will be still released every 3 days, I will skip them and wait for response from either You or some other user - that way hooks would be still updated and files wouldn't be so big as they already are...

**Comment by th3an7** [comment] 2018-10-20 15:57
@AuroraWright It should work once again - restart your device or force close YT app :)

**Comment by Kronopt** [comment] 2018-10-21 11:51
I still use it, and thank you very much for the work you do!

**Comment by smailzhu** [comment] 2018-10-25 06:33
Hi
my Youtube version is 13.34.50 and YouTube Background Playback version is 2.0.5
It's not work when I switch to other app, But there also not error in Xposed Installer log
What do I miss? Or what can I do?
Thanks

**Comment by th3an7** [comment] 2018-10-25 12:34
@smailzhu try updating to some more recent version of YT...
Check logcat for errors - maybe you'll find something there

**Comment by smailzhu** [comment] 2018-10-26 02:18
@th3an7 thank you very much
I use that version because [youtube adaway](https://repo.xposed.info/module/ma.wanam.youtubeadaway) said that test on 13.34.50

**Comment by thebestnom** [comment] 2018-10-28 18:30
Doesnt work on 13.42.52 or is it only me?

**Comment by th3an7** [comment] 2018-10-28 18:39
> Doesnt work on 13.42.52 or is it only me?

No it does not... will add that version in a while... will update this message when it's done...

**Comment by th3an7** [comment] 2018-10-28 21:05
@thebestnom Should work again for .42.52 - as always - restart device or force close YT app


Also: Closing this issue - let's move it to vol.3 as this one is starting to open very slow with such many messages...

**Closed by th3an7** 2018-10-28 21:05 UTC
Labels: bug, downloads, issue reports, question

**Comment by thebestnom** [comment] 2018-10-28 21:47
thanks for the fast reply and fix! great job!
